name: hello_world
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functional_widget_annotation: ^0.10.0
  rxdart: ^0.27.7
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.0.1
  functional_widget: ^0.10.1


flutter:
  uses-material-design: true
